# Generated by Django 3.1.1 on 2020-10-22 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100)),
                ('f_cost', models.IntegerField(max_length=20)),
                ('f_timing', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'facility',
            },
        ),
        migrations.CreateModel(
            name='trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=100)),
                ('t_age', models.IntegerField(max_length=20)),
                ('t_phno', models.IntegerField(max_length=20)),
                ('t_hours', models.IntegerField(max_length=20)),
                ('t_salary', models.IntegerField(max_length=20)),
                ('t_fid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.facility')),
            ],
            options={
                'db_table': 'trainer',
            },
        ),
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=100)),
                ('m_age', models.IntegerField(max_length=20)),
                ('m_phno', models.IntegerField(max_length=20)),
                ('m_time', models.CharField(max_length=20)),
                ('m_years', models.IntegerField(max_length=20)),
                ('m_fid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.facility')),
                ('m_tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.trainer')),
            ],
            options={
                'db_table': 'member',
            },
        ),
    ]
