# Generated by Django 3.1.1 on 2020-10-13 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_id', models.CharField(db_index=True, max_length=10, unique=True)),
                ('f_name', models.CharField(max_length=100)),
                ('f_cost', models.CharField(max_length=20)),
                ('f_timing', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'facility',
            },
        ),
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_id', models.CharField(db_index=True, max_length=10, unique=True)),
                ('m_name', models.CharField(max_length=100)),
                ('m_age', models.CharField(max_length=20)),
                ('m_phno', models.CharField(max_length=20)),
                ('m_time', models.CharField(max_length=20)),
                ('m_years', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'member',
            },
        ),
        migrations.CreateModel(
            name='trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.CharField(db_index=True, max_length=10, unique=True)),
                ('t_name', models.CharField(max_length=100)),
                ('t_age', models.CharField(max_length=20)),
                ('t_phno', models.CharField(max_length=20)),
                ('t_hours', models.CharField(max_length=20)),
                ('t_salary', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'trainer',
            },
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AddField(
            model_name='facility',
            name='f_tid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.trainer'),
        ),
    ]
