# Generated by Django 3.1.1 on 2020-10-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='f_cost',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='m_age',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='m_phno',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='m_years',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='t_age',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='t_hours',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='t_phno',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='t_salary',
            field=models.CharField(max_length=20),
        ),
    ]
