# Generated by Django 3.1.2 on 2020-10-15 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_auto_20201013_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='f_id',
        ),
        migrations.RemoveField(
            model_name='member',
            name='m_id',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='t_id',
        ),
    ]
