# Generated by Django 3.1.1 on 2020-10-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_auto_20201023_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='f_cost',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='facility',
            name='f_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='facility',
            name='f_timing',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='member',
            name='m_age',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='member',
            name='m_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='m_phno',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='m_time',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='member',
            name='m_years',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='t_age',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='t_hours',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='t_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='t_phno',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='t_salary',
            field=models.CharField(max_length=10),
        ),
    ]
